name: CI
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle setup
        run: gradle wrapper
      - name: Test
        run: |
          ./gradlew test